# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Afya' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Afya
	pod 'Alamofire', '~> 5.2'
  target 'AfyaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AfyaUITests' do
    # Pods for testing
  end

end
